name: Get current repo state
description: Get last commit info and output in as string argument.

inputs:
  repo-path:
    required: false
    default: .

outputs:
  last-commit:
    description: Last commit info.
    value: ${{ steps.get-last-commit.outputs.last-commit }}

runs:
  using: composite
  steps:
    -
      id: get-last-commit
      run: cd ${{ inputs.repo-path }} && bash ${{ github.action_path }}/get_last_commit_info.sh
      shell: bash